name: app_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1
  shared_preferences: ^2.2.2
  http: ^1.2.0

  # Ces dépendances sont déjà incluses via Flutter SDK, inutile de les ajouter directement :
  # characters, matcher, material_color_utilities, meta
  # => Supprimées pour éviter les conflits

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpeg

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700